# Generated by Django 4.2.3 on 2023-08-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aout_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='teams/')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twiter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
            ],
        ),
    ]
